# Generated by Django 5.2.18 on 2026-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinvitation',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
    ]
