# Generated by Django 5.2.18 on 2026-10-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, help_text='For Teachers only (e.g. Math, Science)', max_length=100),
        ),
    ]
