# Generated by Django 5.2.18 on 2026-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, choices=[('arabic', 'Arabic'), ('english', 'English'), ('math', 'Mathematics'), ('science', 'Science'), ('social_studies', 'Social Studies'), ('computer', 'Computer Science'), ('art', 'Art'), ('pe', 'Physical Education'), ('religion', 'Religion'), ('second_language', 'Second Language')], help_text='For Teachers only', max_length=50),
        ),
    ]
